WITH CTE AS (

SELECT TO_TIMESTAMP( STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP( STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP( STARTED_AT)) AS HOUR_STARTED_AT,
CASE WHEN DAYNAME(TO_TIMESTAMP( STARTED_AT)) in('Sat','Sun') then 'WEEKEND' else 'BUSINESSDAY' END as DAY_TYPE,
CASE WHEN MONTH(TO_TIMESTAMP( STARTED_AT)) in (12,1,2) THEN 'WINTER' WHEN MONTH(TO_TIMESTAMP( STARTED_AT)) in (3,4,5) THEN 'SPRING' WHEN MONTH(TO_TIMESTAMP( STARTED_AT)) in(6,7,80) THEN 'SUMMER' ELSE 'AUTUM' END AS STATION_OF_YEAR
From {{ source('demo', 'bike') }}
WHERE STARTED_AT !='started_at'
)
select * from CTE