WITH CTE AS (

SELECT TO_TIMESTAMP( STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP( STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP( STARTED_AT)) AS HOUR_STARTED_AT,
{{DAY_TYPE('STARTED_AT')}} AS DAY_TYPE,
{{STATION_OF_YEAR('STARTED_AT')}} AS STATION_OF_YEAR
From {{ source('demo', 'bike') }}

WHERE STARTED_AT !='started_at'
)
select * from CTE